name: Webhook-shitai

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
